### ISSUE TITLE
`@teardown` is run twice

### ISSUE THREAD

**Issue by hexium310** [chitoku-k/zunit#1]
When the assertion doesn't exist in the test, `@teardown` is run twice.

## Reproducing the issue

Run `zunit --verbose minimum.zunit` using the following test:
```zsh
#!/usr/bin/env zunit

@teardown {
    echo teardown
}

@test 'Test' {
    run
}
```

### Expected
The following message is displayed.
```
teardown
```

### Actual
The following message is displayed.
```
teardown
teardown
```

**Comment by chitoku-k** [comment]
Not reproducible in master (fixed in https://github.com/chitoku-k/zunit/commit/47472da7558a9fc2396968b84ca69c8c59cf5259). Make sure you execute `./build.zsh`. Feel free to reopen if you think this is wrong.
```
./zunit --verbose minimum.zunit

Launching ZUnit
ZUnit: 0.8.2
ZSH:   zsh 5.8 (x86_64-pc-linux-gnu)

teardown
‼ Test
  No assertions were run, test is risky

1 tests run in 24ms

Results                        
✔ Passed      0                    
✘ Failed      0                      
‼ Errors      0                      
● Skipped     0                 
‼ Warnings    1 
```
